name: ci

on:
  push:
    branches: [ 'dev' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Asccinema setup
        run: |
          sudo pip3 install asciinema
      - name: Asccinema generation
        id: asccinema
        uses: oscarnevarezleal/asccinema-action/actions/asccicast@dev
        with:
          args: generate -s README.template.md -o README.md
      - name: Giffy
        uses: oscarnevarezleal/asccinema-action/actions/asciicast2gif@dev
        with:
          files: "block-*.json"
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ".asccinema/*.gif"
      - uses: actions/upload-artifact@v2
        with:
          name: block
          path: ".asccinema/*.md"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Automated Change

          # Optional. Used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: ".asccinema/*.* *.md"
